name: abualezz_business_manager
description: "A new Flutter project for business management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.3.0
  path: ^1.8.3
  pdf: ^3.10.8
  printing: ^5.11.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
